#include "/Kernel/Types.HH"
#define TRUE 1
#define FALSE 0
#include "/Kernel/I386/FileLoad.HH"
#include "/Kernel/I386/Cpu.HH"
#include "/Kernel/I386/Ports.HH"
public extern I64 FileLoadTest();
I64 Main(I64 a,I64 b) { return FileLoadTest; }
#include "/Kernel/I386/Heap.HC"
#include "/Kernel/I386/Cpu.HC"
#include "/Kernel/I386/Ata.HC"
#include "/Kernel/I386/RedSea.HC"
#include "/Kernel/I386/FileRead.HC"
#include "/Kernel/I386/FileNames.HC"
#include "/Kernel/I386/Arc.HC"
#include "/Kernel/I386/ArcExpand.HC"
#include "/Kernel/I386/Expand.HC"
#include "/Kernel/I386/FileLoad.HC"
#include "T:/Read.HC"
