#ifndef I386_PUBLIC_TASK_TYPES_INCLUDED
#define I386_PUBLIC_TASK_TYPES_INCLUDED
//One canonical set of public records in each native compilation scope.
#include "/Kernel/HashTypes.HH"
#ifndef CTask
extern class CTask;
#endif
#ifndef CCPU
extern class CCPU;
#endif
#ifndef CJob
extern class CJob;
#endif
#ifndef CHeapCtrl
extern class CHeapCtrl;
#endif
#ifndef CDoc
extern class CDoc;
#endif
#ifndef CDrv
extern class CDrv;
#endif
#ifndef CFPU
extern class CFPU;
#endif
#ifndef CDC
extern class CDC;
#endif
#ifndef CExcept
extern class CExcept;
#endif
#ifndef CBpt
extern class CBpt;
#endif
#ifndef CCtrl
extern class CCtrl;
#endif
#ifndef CMenu
extern class CMenu;
#endif
#ifndef CTaskSettings
extern class CTaskSettings;
#endif
#ifndef CMathODE
extern class CMathODE;
#endif
#ifndef CTSS
extern class CTSS;
#endif
#ifndef CHashFun
extern class CHashFun;
#endif
#ifndef CCmpCtrl
extern class CCmpCtrl;
#endif
#include "/Kernel/WindowScrollTypes.HH"
#include "/Kernel/JobCtrlTypes.HH"
#include "/Kernel/TaskTypes.HH"
#include "/Kernel/CpuTypes.HH"
#endif
