#!/usr/bin/env python3
"""Independent calendar vectors for TempleOS's integer date representation."""
import argparse
from pathlib import Path
import struct

MASK=(1<<64)-1

def trunc_div(a,b):
    return (abs(a)//b)*(-1 if a<0 else 1)

def signed32(value):
    return ((value+(1<<31))&0xFFFFFFFF)-(1<<31)

def year_start(year):
    # Original x64 HolyC lowers signed division by four to arithmetic shift.
    y=year-1
    return year*365+(y//4)-trunc_div(y,100)+trunc_div(y,400)-trunc_div(y,4000)

def months(year):
    return [31,28+int(year_start(year+1)-year_start(year)==366),31,30,31,30,31,31,30,31,30,31]

def decode(day,ticks):
    #Independent year search, without the production average-year estimate.
    lo,hi=-6000000,6000000
    while lo+1<hi:
        mid=(lo+hi)//2
        if year_start(mid)<=day: lo=mid
        else: hi=mid
    year=lo; rest=day-year_start(year); month=1
    for length in months(year):
        if rest<length: break
        rest-=length; month+=1
    #Preserve the original upward quantization, including 24:00 at the last tick.
    units=ticks*864000000//(1<<32)+1
    units,sec10000=divmod(units,100)
    units,sec100=divmod(units,100)
    units,sec=divmod(units,60)
    hour,minute=divmod(units,60)
    fields=bytes((sec10000,sec100,sec,minute,hour,day%7,rest+1,month))
    elapsed=sec10000+100*(sec100+100*(sec+60*(minute+60*hour)))
    encoded=((day&0xFFFFFFFF)<<32)|((elapsed*(1<<32)//864000000)&0xFFFFFFFF)
    first=day-rest
    return (year,int.from_bytes(fields,'little'),encoded,signed32(first),signed32(first+months(year)[month-1])-1,signed32(year_start(year)),signed32(year_start(year+1))-1,day%7,year_start(year))

def generate():
    days=[-(1<<31),-146097,-366,-365,-1,0,1,364,365,(1<<31)-1]
    for year in (1,4,100,400,1600,1900,1999,2000,2023,2024,2100,2400,3999,4000,4001,8000,100000):
        lengths=months(year)
        for month in (1,2,3,12):
            first=year_start(year)+sum(lengths[:month-1])
            days.extend((first,first+lengths[month-1]-1))
    times=(0,1,123456789,0x80000000,0xFFFFFFFE,0xFFFFFFFF)
    rows=[]
    for index,day in enumerate(days):
        ticks=times[index%len(times)]
        rows.append((((day&0xFFFFFFFF)<<32)|ticks,*decode(day,ticks)))
    years=[-(1<<31),-8000,-4000,-1,0,1,4,100,400,4000,(1<<31)-1]
    bcds=[0,1,0x12,0x99,0x1234,0x9999999999999999,0xFEDCBA9876543210]
    text='//Generated by tools/gen-i386-date.py; independent calendar expectations.\n'
    arrays={'date_vectors':rows,'date_year_vectors':[(y,year_start(y)) for y in years],
            'date_bcd_vectors':[(b,sum(((b>>(4*i))&15)*10**i for i in range(16))) for b in bcds]}
    for name,records in arrays.items():
        values=[v&MASK for row in records for v in row]
        data=struct.pack('<'+str(len(values))+'Q',*values)
        text+=f'#define {name.upper()}_COUNT {len(records)}\nU64 *{name}=\n'
        for i in range(0,len(data),32):
            text+='  "'+''.join(f'\\x{v:02X}' for v in data[i:i+32])+'"\n'
        text+=';\n'
    return text

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');args=p.parse_args()
    target=Path(__file__).resolve().parents[1]/'Kernel/I386/DateVectors.HC'
    content=generate()
    if args.check:
        if target.read_text()!=content: raise SystemExit('Regenerate date vectors')
        print('Verified date vectors')
    else: target.write_text(content)
