#!/usr/bin/env python3
"""Pin original lexical state; derive native F64 values from the published policy."""
import argparse
from fractions import Fraction
import hashlib
import json
import math
from pathlib import Path
import re
import struct

ROOT = Path(__file__).resolve().parents[1]
MASK = (1 << 64)-1


def signed(value):
    value &= MASK
    return value-(1 << 64) if value >> 63 else value


def generate():
    original = json.loads((ROOT/'tests/i386/lex-number-values.json').read_text())
    cases = ROOT/'tests/guest/i386-lex-number/Cases.HC'
    source = cases.read_bytes()
    if hashlib.sha256(source).hexdigest() != original['cases_sha256']:
        raise ValueError('Numeric inputs differ from the captured original oracle')
    arrays = re.findall(rb'\{([^}]+)\}', source)
    data = bytes(int(x) for x in arrays[0].split(b','))
    offsets = [int(x) for x in arrays[1].split(b',')[::2]]
    rows = [[int(x, 16) for x in row] for row in original['rows']]
    if len(rows) != len(offsets):
        raise ValueError('Numeric oracle count mismatch')
    differences = []
    pattern = re.compile(r'(?:(\d+)(?:\.(\d*))?|\.(\d+))(?:[eE](-?)(\d*))?')
    for index, (offset, row) in enumerate(zip(offsets, rows)):
        text = data[offset:data.index(0, offset)].decode('ascii')
        if row[0] != 0x104:  #TK_F64 in the captured original token ABI.
            continue
        match = pattern.match(text)
        if match is None:
            raise ValueError(f'Unrecognized floating input: {text}')
        whole, fraction, leading_fraction, negative, exponent = match.groups()
        digits = fraction if fraction is not None else leading_fraction or ''
        mantissa = signed(int((whole or '')+digits))
        power = signed(int(exponent or '0'))
        if negative:
            power = signed(-power)
        power = signed(power-len(digits))
        #Independent conversion/multiply oracle: no target runtime or generated
        #power table is used. I64 conversion and multiplication round to binary64.
        if power > 308:
            scale = math.inf
        elif power < -308:
            scale = 0.0
        elif power >= 0:
            scale = float(Fraction(10**power))
        else:
            scale = float(Fraction(1, 10**-power))
        value = float(mantissa)*scale
        bits = 0x7FF8000000000000 if math.isnan(value) else struct.unpack('<Q', struct.pack('<d', value))[0]
        if bits != row[1]:
            differences.append(dict(case=index, source=text, x64=f'{row[1]:016X}',
                                    native=f'{bits:016X}'))
        row[1] = bits
    native = '//Generated by tools/gen-i386-lex-number.py from the original state and native F64 policy.\n'
    native += f'U64 number_oracle[{len(rows)*6}]={{'+','.join(f'0x{x:016X}' for row in rows for x in row)+'};\n'
    report = json.dumps(dict(cases_sha256=original['cases_sha256'], cases=len(rows),
                            policy='I64 wrapping accumulation; native exact Pow10I64 range; binary64 conversion and multiplication; canonical invalid NaN',
                            differences=differences), indent=2)+'\n'
    return {ROOT/'tests/guest/i386-lex-number/NativeOracle.HC': native,
            ROOT/'tests/i386/lex-number-compatibility.json': report}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, content in generate().items():
        if args.check:
            if path.read_text() != content:
                raise ValueError(f'Stale generated numeric oracle: {path}')
        else:
            path.write_text(content)
    print('PASS numeric oracle check' if args.check else 'Generated native numeric oracle and compatibility report')


if __name__ == '__main__':
    main()
