#!/usr/bin/env python3
"""Generate exact, nearest/even binary64 powers for HolyC's -308..308 contract."""
import argparse
from fractions import Fraction
from pathlib import Path
import struct

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / 'Kernel/I386/Pow10.HC'


def power_bits(exponent):
    value = Fraction(10) ** exponent
    return struct.unpack('<Q', struct.pack('<d', float(value)))[0]


def source():
    lines = ['//Generated by tools/gen-i386-pow10.py; do not edit table entries.',
             '//Nearest/even binary64 powers from exact rational values.',
             'U64 i386_pow10_bits[617]={']
    values = [f'0x{power_bits(i):016X}' for i in range(-308, 309)]
    for i in range(0, len(values), 4):
        lines.append('  '+','.join(values[i:i+4])+(',' if i+4<len(values) else ''))
    lines += ['};', '', 'F64 Pow10I64(I64 exponent)', '{',
              '  U64 bits;', '  if (exponent>308) bits=0x7FF0000000000000;',
              '  else if (exponent<-308) bits=0;',
              '  else bits=i386_pow10_bits[exponent+308];',
              '  return bits(F64);', '}', '']
    return '\n'.join(lines)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = source()
    if args.check:
        if TARGET.read_text() != expected:
            raise SystemExit('Powers-of-ten table differs from exact generator')
        print('PASS: 617 powers-of-ten entries match exact rational generation')
    else:
        TARGET.write_text(expected)
