#!/usr/bin/env python3
"""Generate independent vectors for retained public math integration."""
import argparse
from pathlib import Path
import struct
from i386_f64_oracle import make_unary_oracle
from i386_log_oracle import make_log_oracle
from i386_integer_oracle import make_integer_math_oracle


def generate():
    unary=make_unary_oracle(1024)
    integral=[(row[0],*row[4:]) for row in list(struct.iter_unpack('<8Q',unary[:1024*64]))[768:832]]
    logs=list(struct.iter_unpack('<4Q',make_log_oracle()))
    arrays={'public_integral_vectors':integral,
            'public_log_vectors':logs[768:800]+logs[832:864],
            'public_multiple_vectors':list(struct.iter_unpack('<7Q',make_integer_math_oracle()[1024*96:])),
            'public_power_vectors':list(struct.iter_unpack('<Q',unary[1024*64:]))}
    text='//Generated by tools/gen-i386-public-math.py; independent numerical expectations.\n'
    for name,rows in arrays.items():
        values=[v for row in rows for v in row]
        data=struct.pack('<'+str(len(values))+'Q',*values)
        text+=f'U64 *{name}=\n'
        for index in range(0,len(data),32):
            text+='  "'+''.join(f'\\x{v:02X}' for v in data[index:index+32])+'"\n'
        text+=';\n'
    return text

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    path=Path(__file__).resolve().parents[1]/'Kernel/I386/PublicMathVectors.HC'
    result=generate()
    if args.check:
        if path.read_text()!=result: raise SystemExit('Regenerate retained public math vectors')
        print('Verified retained public math vectors')
    else: path.write_text(result)
